name: {{prefix.snakeCase()}}_api
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.2.1
  copy_with_extension: ^4.0.0
  dio: ^4.0.6
  get_it: ^7.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1
  json_annotation: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  pinch_lints:
    git:
      url: git@bitbucket.org:justpinch/pinch-lints.git
      ref: 1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  copy_with_extension_gen: ^4.0.1

flutter:

