name: cli
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  yaml: ^3.1.1
  mason: ^0.1.0-dev.28
  pre_hooks:
    path: pre_hooks

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.4
