name: {{prefix.snakeCase()}}_data
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal packages
  {{prefix.snakeCase()}}_api:
    path: ../{{prefix.snakeCase()}}_api
  {{prefix.snakeCase()}}_storage:
    path: ../{{prefix.snakeCase()}}_storage
  {{prefix.snakeCase()}}_domain:
    path: ../{{prefix.snakeCase()}}_domain

  copy_with_extension: ^4.0.0
  build_runner: ^2.1.8
  copy_with_extension_gen: ^4.0.1
  logger: ^1.1.0
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  pinch_lints:
    git:
      url: git@bitbucket.org:justpinch/pinch-lints.git
      ref: 1.0.0

flutter:

