name: easy_components
description: Makes it easier to create classes and DTOs
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'


dependencies:
  yaml: ^3.1.1
  mason: ^0.1.0-dev.28
  pre_hooks:
    path: pre_hooks
  recase: ^4.0.0
  analyzer: ^4.6.0
  mocktail: ^0.3.0

executables:
  easy_components:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.4
  build_runner: ^2.2.0
  json_serializable: ^6.0.0

